spring.application.name=ai-tech-lead



# Server settings
server.port=8085

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}

# Google Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}

gemini.api.url=${GEMINI_API_URL}





